### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libavformat-57.so" not found

### ISSUE THREAD

**Issue by Shehata-Inova** [OpenWatch/FFmpegWrapper-Android#4]
**System.loadLibrary("FFmpegWrapper");**

java.lang.UnsatisfiedLinkError: dlopen failed: library "libavformat-57.so" not found
06-14 17:38:40.507 26850-26850/com.n2me.android E/AndroidRuntime:     at java.lang.Runtime.loadLibrary(Runtime.java:372)
06-14 17:38:40.507 26850-26850/com.n2me.android E/AndroidRuntime:     at java.lang.System.loadLibrary(System.java:1076)
06-14 17:38:40.507 26850-26850/com.n2me.android E/AndroidRuntime:     at net.openwatch.ffmpegwrapper.FFmpegWrapper.<clinit>(FFmpegWrapper.java:45)

**Comment by Gigibit** [comment]
You have to load .so file.
Follow this:

https://proandroiddev.com/android-ndk-how-to-integrate-pre-built-libraries-in-case-of-the-ffmpeg-7ff24551a0f
